ERPCRM/Models/Pedido.cs
using System;
using System.ComponentModel.DataAnnotations;


namespace ERPCRM.Models
{
    public class Pedido
    {
        [Key]
        [Display(Name = "ID do Pedido")]
        public int id { get; set; }
        [Required]
        public int idUsuario { get; set; }
        [Display(Name = "Nome")]
        public string nomeUsuario { get; set; }
        public int id_status { get; set; }
        [Display(Name = "Status do pedido")]
        public string statusDescricao { get; set; }
        [Display(Name = "Data de Cadastro")]
        public DateTime dteIns { get; set; }
        public Boolean ativo { get; set; }

    }
}

ERPCRM/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERPCRM.Models;
using ERPCRM.Repository;

namespace ERPCRM.Controllers
{
    public class PedidoController : Controller
    {
        // GET: Pedido
        [Authorize]
        public ActionResult Index()
        {
            PedidoRepository objPedidoRep = new PedidoRepository();

            return View(objPedidoRep.ListaTodos());
        }

        // GET: Pedido/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            PedidoRepository objPedidoRep = new PedidoRepository();
            PedidoItemRepository objPedidoItemRep = new PedidoItemRepository();
            PedidoItens objPedidoItens = new PedidoItens();

            objPedidoItens.pedido = objPedidoRep.Dados(id);
            objPedidoItens.listPedidoItem = objPedidoItemRep.ListaTodos(id);

            if (objPedidoItens == null)
            {
                ModelState.AddModelError("", "O pedido não está cadastrado no sistema.");
                return RedirectToAction("Index");
            }
            else
                return View(objPedidoItens);
        }

        // GET: Pedido/Create
        [Authorize]
        public ActionResult Create()
        {

            int retornoCadastro = 0;
            PedidoRepository objPedidoRep = new PedidoRepository();

            retornoCadastro = objPedidoRep.Inserir(1);
            if(retornoCadastro > 0)
                return RedirectToAction("Details", "Pedido", new { id = retornoCadastro });
            else
            {
                ModelState.AddModelError("", "Infelizmente não foi possível criar um novo pedido.");
                return RedirectToAction("Index", "Pedido");
            }
            
        }

        // POST: Pedido/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pedido/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Pedido/Edit/5
        [HttpPost]
        [Authorize]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // Verificar se o pedido está finalizado

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pedido/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Pedido/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // Verificar se o pedido está finalizado

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ERPCRM/Controllers/PedidoItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERPCRM.Models;
using ERPCRM.Repository;

namespace ERPCRM.Controllers
{
    public class PedidoItemController : Controller
    {
        // GET: PedidoItem
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        // GET: PedidoItem/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            PedidoItem objPedido = new PedidoItem();
            PedidoItemRepository objPedidoItemRep = new PedidoItemRepository();

            objPedido = objPedidoItemRep.Dados(id);

            if(objPedido != null)
                return View(objPedido);
            else
                return RedirectToAction("Index","Pedido");
        }

        // GET: PedidoItem/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: PedidoItem/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(PedidoItem objPedidoItemform)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int retorno = 0;
                    PedidoItemRepository objPedidoItemRep = new PedidoItemRepository();

                    retorno = objPedidoItemRep.Inserir(objPedidoItemform);

                    if (retorno == 0)
                    {
                        ModelState.AddModelError("", "Ocorreu um erro, não foi possível cadastrar o produto no pedido, erro no processo de cadastro.");
                    }
                    else { 
                        return RedirectToAction("Details", "Pedido", new { id = objPedidoItemform.id_pedido });
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Ocorreu um erro, não foi possível cadastrar o produto no pedido, erro nos dados do produto.");
                }

                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("", "Ocorreu um erro, não foi possível cadastrar o produto no pedido.");
                return RedirectToAction("Index");
            }
        }

        // GET: PedidoItem/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            PedidoItem objPedidoitem = new PedidoItem();
            PedidoItemRepository objPedidoItemRep = new PedidoItemRepository();

            objPedidoitem = objPedidoItemRep.Dados(id);

            if (objPedidoitem != null)
            {
                return View(objPedidoitem);
            } else {
                ModelState.AddModelError("", "Ocorreu um erro, não foi possível encontrar o item.");
                return RedirectToAction("Index", "Pedido");
            }
        }

        // POST: PedidoItem/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(PedidoItem objPedidoItemForm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int retorno = 0;
                    PedidoItemRepository objPedidoItemRep = new PedidoItemRepository();

                    retorno = objPedidoItemRep.Alterar(objPedidoItemForm);

                    if (retorno == 0)
                    {
                        ModelState.AddModelError("", "Ocorreu um erro, não foi possível alterar o produto no pedido, erro no processo de alteração.");
                    }
                    else
                    {
                        return RedirectToAction("Details", "Pedido", new { id = objPedidoItemForm.id_pedido });
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Ocorreu um erro, não foi possível alterar o produto no pedido, erro nos dados do produto.");
                }

                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("", "Ocorreu um erro, não foi possível alterar o item.");
                return RedirectToAction("Details", "Pedido", new { id = objPedidoItemForm.id_pedido});
            }
        }

        // GET: PedidoItem/Delete/5
        [Authorize]
        public ActionResult Delete()
        {
            return RedirectToAction("Index", "Pedido");
        }

        // POST: PedidoItem/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id, int idPedido)
        {
            try
            {
                int retorno = 0;
                PedidoItemRepository objPedidoItemRep = new PedidoItemRepository();

                retorno = objPedidoItemRep.Apagar(id);

                if (retorno == 0)
                {
                    ModelState.AddModelError("", "Ocorreu um erro, não foi possível alterar o produto no pedido, erro no processo de alteração.");
                }
                else {
                    return RedirectToAction("Details", "Pedido", new { id = idPedido });
                }

                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("", "Ocorreu um erro, não foi possível apagar o item.");
                return RedirectToAction("Details", "Pedido", new { id = idPedido });
            }
        }
    }
}

ERPCRM/Views/Pedido/Details.cshtml
@model ERPCRM.Models.PedidoItens

@{
    ViewBag.Title = "Details";
}

<h2>Dados do pedido</h2>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.pedido.nomeUsuario)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.pedido.nomeUsuario)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.pedido.statusDescricao)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.pedido.statusDescricao)
    </dd>
 </dl> 

<table class="table">

    <thead>
        <tr>
            <th>
                Produto
            </th>
            <th>
                Quantidade
            </th>
            <th>
                Valor (unitário)
            </th>
        </tr>
    </thead>

    <tbody>

        @foreach (var item in Model.listPedidoItem)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.nomeProduto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.quantidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.valor_unitario)
                </td>

                <td>
                    @Html.ActionLink("Dados", "Details", "PedidoItem", new { id = item.id }) |

                    @if (Model.pedido.status == 0 && Model.pedido.ativo == true)
                    {
                        @Html.ActionLink("Alterar", "Edit", "PedidoItem", new { id = item.id }) |
                        @Html.ActionLink("Apagar", "Delete", "PedidoItem", new { id = item.id })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

ERPCRM/Views/Pedido/Index.cshtml
@model IEnumerable<ERPCRM.Models.Pedido>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Novo Pedido", "Create", "Pedido", new { id = 1 })
</p>
<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.nomeUsuario)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.statusDescricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dteIns)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ativo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.nomeUsuario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.statusDescricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dteIns)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ativo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Dados", "Details", new { id=item.id }) |

            @if(item.id_status != 1 && item.ativo == true)
            { 
                @Html.ActionLink("Apagar", "Delete", new { id=item.id })
            }
        </td>
    </tr>
}

</table>